<a href="https://colab.research.google.com/github/Yasha-Wadhawan/PW/blob/main/Numpy_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy is the main buildig blocks of all the libraries related to data in python


In [ ]:
# NumPy Arrays
# numpy array come in two parts 1 is one dimentional vectors  and 2nd is two dimentional matrix

In [ ]:
# cast a normal python list into an array

l1 = [1,2,3,4,5]
import numpy as np
print(np.array(l1))            # array
print(l1)                      # list
print(type(l1))

arr = np.array(l1)
print(arr)
print(type(arr))


[1 2 3 4 5]
[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# two dimentional array or matrix

l2 = [[1,2,3],[4,5,6],[7,8,9],[0,0,0]]
arr2 = np.array(l2)
print(arr2)                 # the two brackets in the output proves that it is a tow d array or matrix
print(type(arr2))



[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 0 0]]
<class 'numpy.ndarray'>


In [ ]:
# numpy built in generation methods to create arrays

# most common way to create a numpy array is using
print(np.arange(0,10))                                  # it is just like python range function
print(np.arange(0,20,3))


[0 1 2 3 4 5 6 7 8 9]
[ 0  3  6  9 12 15 18]


In [ ]:
# some specific types of arrays

In [ ]:
# arrays of all zeros
print(np.zeros(3))
print("\n")
print(np.zeros((3,4)))                # 2 brackets will come in case of 2d array


[0. 0. 0.]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# arrays of all ones
print(np.ones(5))
print(np.ones((5,7)))

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# linspace returns EVENLY SPACED numbers over a specified intervals
# there is a difference bw a linspace and arrange function

print(np.linspace(1,100,5))                             # in linspace np.linspace((start,end,num)) # here end number is included # num means The number of samples needed to generate within the interval. The default value is 50.
# start and stop is compulsory rest all the parameters are optional

print(np.linspace(1,100))              # and  keep in mind it is a 1D array as it has one bracket

# the difference bw the 3rd argument of arange function and linspace function in arange it is the no. of steps (same as range function) # in linspace it is number(outputs / default is 50) of points you wants


[  1.    25.75  50.5   75.25 100.  ]
[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]


In [ ]:
# identity matrix using numpy

np.eye(4)                 # output is a 2D array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#The random.rand() is a numpy library function that returns an array of random samples from the uniform distribution over [0,1].
#It allows dimensions as an argument and returns an array of specified dimensions.
# Uniform distribution means a number has equally likely outcomes eg roll dice all output has equally likely outcomes.
# here random is an object of some class and rand is the method.
# random has a lot of methods

import numpy as np
print(np.random.rand(6))
print("\n\n")
arr = np.random.rand(6,7)
print(arr)
print("\n\n\n")
print(np.random.rand(2,4,6))

[0.055662   0.720992   0.99088547 0.88247979 0.31563144 0.35787848]



[[0.73275585 0.32613199 0.32055063 0.96105942 0.91743673 0.49769609
  0.26328839]
 [0.84227632 0.94722738 0.42051239 0.89494533 0.99694409 0.38127033
  0.47277708]
 [0.09468635 0.80852014 0.31505726 0.48014284 0.65375355 0.88641249
  0.60024029]
 [0.39788645 0.15749261 0.57086079 0.63880578 0.86344638 0.90487417
  0.20838583]
 [0.06439516 0.14026771 0.53852395 0.16584311 0.41463565 0.31249633
  0.78539139]
 [0.39580277 0.71058388 0.04605986 0.95844241 0.60387328 0.10602037
  0.00810677]]




[[[0.21615368 0.6826059  0.22528577 0.18526911 0.43902484 0.8414224 ]
  [0.54143908 0.41393713 0.32312267 0.03307525 0.52497232 0.42981248]
  [0.47737077 0.38500058 0.2799955  0.99418101 0.648111   0.70835696]
  [0.70116592 0.26852592 0.64420973 0.85364415 0.64512867 0.13821468]]

 [[0.17907079 0.88599999 0.19204688 0.5066115  0.94648393 0.66964857]
  [0.80004088 0.46788457 0.08770264 0.35058195 0.05362985 0.07061796]
  [0.01513

In [ ]:
#The random.randn() is a numpy library function that returns an array of random samples from the standard normal distribution.
#It allows specified dimensions as an argument and returns an array of specified dimensions.
#The np.random.randn() function returns all the samples in float form, which are from the univariate “normal” (Gaussian) distribution of mean 0 and variance 1.
import numpy as np
arr = np.random.randn(6)
print(arr)
print("\n\n")
arr1 = np.random.randn(3,6)
print(arr1)
print("\n\n")
arr2 = np.random.randn(2,4,8)
print(arr2)



[-0.1734804  -0.57243444  0.13015047 -1.82153262 -0.28508466 -0.69080378]



[[ 1.55736677 -0.57474084 -0.39037593  2.54533059  0.69629027 -1.47140192]
 [ 0.45864663  0.08330505 -0.81322679  0.31776608 -0.39514501  0.09537329]
 [ 0.3708675  -0.60383776  0.35162868  1.14004588  1.87644441  0.03145152]]



[[[ 0.0670639  -0.20538005 -0.17701948  1.17202549 -0.15721036
    1.29334766  1.2204051  -1.36280677]
  [ 0.08596033 -0.07005322 -0.95844551 -0.76900008  0.70695725
    0.52852218  0.97929045 -0.49718254]
  [-0.36755642  0.64801148 -0.708616    0.95948916 -1.07926578
   -0.54380361  1.60616041  1.11748295]
  [ 0.30383531 -0.51862112  0.33677602 -0.70900459 -1.05588948
   -0.2339431  -0.83624789  0.45548479]]

 [[-1.82658331 -0.74977016 -1.85749389 -1.02564355 -1.82993603
    1.29037604 -0.83026951 -1.49886202]
  [ 1.63252802  0.29939857 -0.89269574 -0.8340092   0.04396566
   -0.10323862  0.33043524  0.06947743]
  [-0.95494217  1.01148507  0.28702135  0.28170229  0.52154474
    0.06463

In [ ]:
#The random.randint() is a NumPy library function that returns an array of random integers that are discrete uniform distribution of the specified dtype in the half-open interval [low, high).
# inclusive on low end and exclusive on the high end
# By default the value of high is None.
#If NO value is used for high param then the results are from [0, low).

import numpy as np
arr = np.random.randint(9)
print(arr)
print("\n")
arr1 = np.random.randint(low=2,high=8,size=4)
print(arr1)
print("\n")
arr2 = np.random.randint(low=3,high=99,size=(4,8))
print(arr2)
print("\n")
arr3 = np.random.randint(low=6, high=36, size=(2,4,8))
print(arr3)


6


[5 2 6 5]


[[42 72 41  9 60 81 71 76]
 [25 21 94 54 21 47 23 32]
 [72 11 26 75 64 65 65 78]
 [26 29  3 40 66 48 60 58]]


[[[20 27 17 26 35 25 14 35]
  [13 21  6 11 19 30 35 24]
  [35 14 21 24  7 34  8 17]
  [28 21 34 25 35 29 31 17]]

 [[ 6 24 22 33 16 16 14 31]
  [13  8 18 10 35 26  7 19]
  [12  6 13 17 26 15 32 18]
  [23 35 18 21 27 14 28 11]]]


In [ ]:
# few useful methods and attributes of an array

In [ ]:
arr1 = np.arange(15)                  # 1D array upto 15
print(arr1)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
# reshape method return an array containing the same data of new shape
import numpy as np
arr1 = np.random.randint(low=10,high= 100, size=(5,8))
print(arr1)
print("\n")
arr2 = arr1.reshape(2,20)
print(arr2)
print("\n")
arr3 = arr1.reshape(5,3)                        # this reshape is not possible as total number of elements must be same
print(arr3)


[[53 15 94 96 75 48 61 70]
 [11 62 71 15 34 17 40 68]
 [47 33 57 17 99 72 79 25]
 [60 88 90 17 95 55 57 93]
 [70 22 36 16 19 86 28 50]]


[[53 15 94 96 75 48 61 70 11 62 71 15 34 17 40 68 47 33 57 17]
 [99 72 79 25 60 88 90 17 95 55 57 93 70 22 36 16 19 86 28 50]]




ValueError: ignored

In [ ]:
# max method
import numpy as np
arr1 = np.random.randint(4,100000, (4,8))
print(arr1)
print("\n")
print(np.max(arr1))



[[47376 49237 59488  6514 39602 40206  4206 74365]
 [24225 33514 76673 47847 93670 73588 27705 30467]
 [63211 28929  6170 20941  2755 70158 17131 29776]
 [73476 51266  5584  6030 60035 21735 96286 25923]]


96286


In [ ]:
# min method
import numpy as np
arr1 = np.random.randint(4,100000, (4,8))
print(arr1)
print("\n")
print(np.min(arr1))


[[22964 17026 87839 81637 33841 10323 24664 41189]
 [22391 29887 98694 52475 96700 68175 54968 47094]
 [72237 44753 25057 87511 69970 49523 63066 32151]
 [22750 34622 99249 25724 51764 20788 59067 27664]]


10323


In [ ]:
# find location of max and min values

print(np.argmin(arr1))


29


In [ ]:
# find the shape of the matrix
import numpy as np
print(np.shape(arr1))                             # in shape counting starts from 1 and so on, Not 0

(4, 8)


In [ ]:
# reshape an array
import numpy as np

arr2 = arr1.reshape(8,4)                                  # in reshape as well the counting starts from 1 and so on, NOT 0
print(arr2)
print("\n")
arr2 = arr1.reshape(2,16)
print(arr2)
print("\n")
arr2 = arr1.reshape(32,1)
print(arr2)

[[22964 17026 87839 81637]
 [33841 10323 24664 41189]
 [22391 29887 98694 52475]
 [96700 68175 54968 47094]
 [72237 44753 25057 87511]
 [69970 49523 63066 32151]
 [22750 34622 99249 25724]
 [51764 20788 59067 27664]]


[[22964 17026 87839 81637 33841 10323 24664 41189 22391 29887 98694 52475
  96700 68175 54968 47094]
 [72237 44753 25057 87511 69970 49523 63066 32151 22750 34622 99249 25724
  51764 20788 59067 27664]]


[[22964]
 [17026]
 [87839]
 [81637]
 [33841]
 [10323]
 [24664]
 [41189]
 [22391]
 [29887]
 [98694]
 [52475]
 [96700]
 [68175]
 [54968]
 [47094]
 [72237]
 [44753]
 [25057]
 [87511]
 [69970]
 [49523]
 [63066]
 [32151]
 [22750]
 [34622]
 [99249]
 [25724]
 [51764]
 [20788]
 [59067]
 [27664]]


In [ ]:
# how to know what data type you have in your array

print(arr1.dtype)

int64


In [ ]:
# another way to represent random object and use random object module

from numpy.random import randint                  # can write 'as' as well
print(randint(3,44))

11


In [ ]:
# Numpy Array Indexing
# indexing in numpy array is a lot like indexing in Python List
# here indexing starts from 0 itself of both rows and columns

import numpy as np

In [ ]:
arr = np.arange(0,11)
print(arr)

print(arr[7])
# slice notation same as list slice notation
print(arr[3:8])
print(arr[3:8:2])
print(arr[ : ])       # in the entire indexing of the array if NO digit is writte and it is empty it means all the values of that part will come
print(arr[ :6])
print(arr[4: ])

[ 0  1  2  3  4  5  6  7  8  9 10]
7
[3 4 5 6 7]
[3 5 7]
[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5]
[ 4  5  6  7  8  9 10]


In [ ]:
# Numpy array is different from python list because of its ability to broadcast
# broadcasting eg

import numpy as np

arr = np.arange(0,11)
print(arr)

arr[:6] = 99
print(arr)
print("\n")
arr = np.arange(0,11)

slice_of_arr = arr[ :6]         # here change in the slice_of_arr will also change the original array # as numpy will NOT automatically set the copy of array, you havr to specifically indicate that you want a copy using copy method
slice_of_arr[ : ] = 88
print(slice_of_arr)
print(arr)

# all the above is a type of broadcasting
# if you want to create a seperate array from another array use copy method

print("\n")
arr = np.arange(0,11)
arr_copy = arr.copy()
print(arr_copy)
arr_copy[ : ] = 44
print(arr_copy)
print(arr)                        # now using array copy method NO changes in the original array


[ 0  1  2  3  4  5  6  7  8  9 10]
[99 99 99 99 99 99  6  7  8  9 10]


[88 88 88 88 88 88]
[88 88 88 88 88 88  6  7  8  9 10]


[ 0  1  2  3  4  5  6  7  8  9 10]
[44 44 44 44 44 44 44 44 44 44 44]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Indexing  a 2D Array otherwise know as matrix

arr2d = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(arr2d)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# 2 general format for grabing elements from  2D array 1 double bracket format 2 single bracket format with a comma

print(arr2d[1][1])
print(arr2d[1,1])                            # in all the array after comma there is always a colum # usually used


5
5


In [ ]:
# How to get chunks od elements from matrix eg want a sub matrix from this matrix or grab entire section of elements
print(arr2d)
print("\n")
print(arr2d[ :2,1: ])                    # here before comma is the row and after comma is the column and : works exactly like slice notation
print("\n")
print(arr2d[1:3,1: ])
print("\n")
print(arr2d[1:3,1:2])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[2 3]
 [5 6]]


[[5 6]
 [8 9]]


[[5]
 [8]]


In [ ]:
# Conditional Selection
import numpy as np
arr = np.arange(1,11)
print(arr)
print(arr>6)                         # take arr and combine it with comparision operators to get a boolean array out of this # the dtype of this output will be bool
bool_arr = arr>6
print(bool_arr.dtype)

# now we can use the above to do conditional selection
print(arr[bool_arr])                                       # using this we only get the result which is True bool value # this is called conditional selection

# insead of doing this in 2 steps you can do this in 1 step ie put the condition and have that selection
print(arr[arr>6])

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False False  True  True  True  True]
bool
[ 7  8  9 10]
[ 7  8  9 10]


In [ ]:
# calling method off another method
import numpy as np
array_2d = np.arange(50).reshape(5,10)
print(array_2d)

# now practice grabing random chunks out of it
print(array_2d[1:5,3:7])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[13 14 15 16]
 [23 24 25 26]
 [33 34 35 36]
 [43 44 45 46]]


In [ ]:
# Numpy Operations


In [ ]:
# array with array operation can be used with arithmatic  singhs from python

arr = np.arange(0,11)
print(arr)
print(arr+arr)             # adding an array to itself so the number is doubled
print(arr-arr)
print(arr*arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0 0]
[  0   1   4   9  16  25  36  49  64  81 100]


In [ ]:
# perform array with scalar operations scalar means a single number
# the numpy will broadcast the number in every element of the array
print(arr+100)
print(arr*100)
print(arr)
print(arr**6)
print(arr>6)

[100 101 102 103 104 105 106 107 108 109 110]
[   0  100  200  300  400  500  600  700  800  900 1000]
[ 0  1  2  3  4  5  6  7  8  9 10]
[      0       1      64     729    4096   15625   46656  117649  262144
  531441 1000000]
[False False False False False False False  True  True  True  True]


In [ ]:
# on certain mathematical operations instead of giving an error numpy gives a warning
import numpy as np
#print(1/0)                               # on this an actual error will be returned
print(arr/0)                                  # numpy will not give the same error it will issue a warning we still get the output and nan will also come
print(1/arr)                                # in this case it will show infinity instead of null




[nan inf inf inf inf inf inf inf inf inf inf]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1       ]


<ipython-input-20-577017e6f746>:4: RuntimeWarning: divide by zero encountered in true_divide
  print(arr/0)                                  # numpy will not give the same error it will issue a warning we still get the output and nan will also come
<ipython-input-20-577017e6f746>:4: RuntimeWarning: invalid value encountered in true_divide
  print(arr/0)                                  # numpy will not give the same error it will issue a warning we still get the output and nan will also come
<ipython-input-20-577017e6f746>:5: RuntimeWarning: divide by zero encountered in true_divide
  print(1/arr)


In [ ]:
# numpy universal array function which are just mathematical operations you can use to perform the operation and broadcast in the entire array.
print(np.sqrt(arr))
print("\n")
print(np.exp(arr))
print("\n")
print(np.max(arr))
print(np.min(arr))
print("\n")
print(np.sin(arr))
print("\n")
print(np.log(arr))                # here infinity will show and runtime warning


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]


[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]


10
0


[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]


[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]


<ipython-input-29-8d9717cf6390>:11: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))
